### PR TITLE
adds a note about required line change for docker builds for electron…

### PR DESCRIPTION
**Pull request by dgershman**
… on m1

### CODE REVIEW

**Comment by anmavrid** [comment]
Hi @dgershman, 

Thanks for opening this PR. 

With this change, you can use a MAC (M1 and beyond) to build a Linux executable, right?

**Comment by dgershman** [comment]
> Hi @dgershman,
> 
> is this needed for M1 architectures? I see that you closed this PR.

I suppose yes, however, the steps here generate a Linux binary, so I'm not sure how helpful it is.  I was initially trying to generate a MacOS M1 binary using these steps and then realized that it wasn't going to do that.

**Comment by anmavrid** [comment]
> > Hi @dgershman,
> > is this needed for M1 architectures? I see that you closed this PR.
> 
> I suppose yes, however, the steps here generate a Linux binary, so I'm not sure how helpful it is. I was initially trying to generate a MacOS M1 binary using these steps and then realized that it wasn't going to do that.

Yes, this will generate a Linux binary using a MacOS system.

To generate a MacOS binary, we have this script: https://github.com/NASA-SW-VnV/fret/blob/master/tools/Scripts/FRETExecutables/generate_executable_for_MacOS.sh

We have not tested it on an M1 machine yet but we will be able to do that soon.

**Comment by dgershman** [comment]
Ok I will test this and provide comments!

**Comment by anmavrid** [comment]
> Ok I will test this and provide comments!

Thank you!

I am closing this PR.

**Pull request closed without merging**
